# Generated by Django 3.2 on 2021-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='uuid',
            field=models.CharField(max_length=36, unique=True, verbose_name='UUID'),
        ),
    ]
