# Generated by Django 3.2 on 2021-05-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_equipmentcard_equipmentfeature_equipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfeature',
            name='equipment_card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.equipmentcard', verbose_name='Учетная карточка'),
            preserve_default=False,
        ),
    ]
