# Generated by Django 3.2 on 2021-05-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_equipmentfeature_equipment_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentfeature',
            options={'ordering': ['name'], 'verbose_name': 'Характеристика оборудования', 'verbose_name_plural': 'Характеристики оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['title'], 'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
    ]
